services:
  celery_worker:
    build: .
    container_name: codeboost_celery_worker
    entrypoint: []
    command: >
      sh -c "
      echo 'Waiting for Judge0...';
      until curl -s -o /dev/null -w '%{http_code}' http://${LINUX_JUDGE0_IP}:2358/languages | grep -q 200; do
        echo 'Judge0 not ready, retrying in 5s...';
        sleep 5;
      done;
      echo 'Judge0 is up. Starting worker.';
      celery -A CodeBoost worker --loglevel=info --pool=solo -n worker@%h --prefetch-multiplier=1
      "
    env_file:
      - .env
    restart: always








# To rebuild the container after git pull
# sudo docker compose -f docker-compose-code-engine.yml up -d --build