# Generated by Django 6.0.2 on 2026-03-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
