# Generated by Django 6.0.2 on 2026-04-09 20:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_contest_registration_deadline'),
        ('problem', '0010_alter_problem_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='moderators',
            field=models.ManyToManyField(blank=True, null=True, related_name='moderator_of_contests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contest',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='joined_contests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(blank=True, null=True, related_name='contests', to='problem.problem'),
        ),
    ]
