# Generated by Django 6.0.2 on 2026-04-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_alter_contest_moderators_alter_contest_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='private_key',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
