# Generated by Django 6.0.2 on 2026-09-01 09:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_contest_is_private_contest_private_key'),
        ('problem', '0013_tags_problem_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['is_private'], name='contest_con_is_priv_f7965e_idx'),
        ),
    ]
