# Generated by Django 6.0.2 on 2026-02-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_codesnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rating',
            field=models.IntegerField(blank=True, default=1200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='solved_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
