# Generated by Django 6.0.2 on 2026-04-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_emailtemplate'),
        ('problem', '0010_alter_problem_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='solved_problems',
            field=models.ManyToManyField(blank=True, null=True, related_name='solved_by', to='problem.problem'),
        ),
    ]
