# Generated by Django 6.0.2 on 2026-05-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_userprofile_solved_problems'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userprofile',
            name='home_userpr_rating_c9adf2_idx',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
