# Generated by Django 6.0.2 on 2026-05-04 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0011_remove_submission_problem_sub_user_id_f6e9cf_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('avatar', models.URLField(blank=True, default='https://res.cloudinary.com/dxd9uxsfv/image/upload/v1770963972/bjngg2xwjfd0vp69xv45.jpg', null=True)),
                ('bio', models.TextField(blank=True, max_length=1000, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=300, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('social', models.URLField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, default=1200, null=True)),
                ('solved_count', models.IntegerField(blank=True, default=0, null=True)),
                ('solved_problems', models.ManyToManyField(blank=True, null=True, related_name='solved_by', to='problem.problem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['rating'], name='user_profil_rating_f465c6_idx')],
            },
        ),
    ]
