# Generated by Django 6.0.2 on 2026-03-06 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='slug',
        ),
    ]
