# Generated by Django 6.0.2 on 2026-03-07 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_remove_problem_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='input',
            new_name='problem_input',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='output',
            new_name='problem_output',
        ),
    ]
