# Generated by Django 6.0.2 on 2026-03-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_rename_input_problem_problem_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('challenging', 'Challenging')], default='easy', max_length=55),
        ),
    ]
