# Generated by Django 6.0.2 on 2026-03-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_alter_problem_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(default='Pending', max_length=60),
        ),
    ]
