# Generated by Django 6.0.2 on 2026-03-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_alter_submission_verdict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='execution_time',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='memory_used',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
