# Generated by Django 6.0.2 on 2026-03-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_alter_submission_execution_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='testcase_details',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='problem',
            name='memory_limit',
            field=models.FloatField(default=512),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.FloatField(default=1.0),
        ),
    ]
