# Generated by Django 6.0.2 on 2026-03-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0008_submission_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
