# Generated by Django 6.0.2 on 2026-05-01 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_contest_is_private_contest_private_key'),
        ('problem', '0010_alter_problem_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='submission',
            name='problem_sub_user_id_f6e9cf_idx',
        ),
        migrations.RemoveIndex(
            model_name='submission',
            name='problem_sub_problem_26f37c_idx',
        ),
        migrations.AlterField(
            model_name='submission',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contest.contest'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problem.problem'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['contest', '-submitted_at'], name='problem_sub_contest_a6d620_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['contest', 'user', 'problem', 'submitted_at'], name='problem_sub_contest_7629b9_idx'),
        ),
    ]
