# Generated by Django 6.0.2 on 2026-05-07 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_contest_is_private_contest_private_key'),
        ('problem', '0011_remove_submission_problem_sub_user_id_f6e9cf_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'verdict', 'problem', 'submitted_at'], name='problem_sub_user_id_ff6fa1_idx'),
        ),
    ]
