# Generated by Django 6.0.2 on 2026-09-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0012_submission_problem_sub_user_id_ff6fa1_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='problems', to='problem.tags'),
        ),
    ]
